#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f $userresources ]; then
    xrdb -merge $userresources
fi

# wm-independent stuff
xset s off
numlockx &

[ -z "$WM" ] && WM="i3"
case "$WM" in
    "i3")
        exec i3
        break
        ;;
    "dwm")
        xcompmgr &
        mpd &
        unclutter &
        setwall &
        dunst &
        nm-applet &
        exec dwm
        break
        ;;
esac

