#!/usr/bin/env sh
SALTRICED="/usr/share/saltrice"
[ ! -z "$SCRIPTSD" ] && echo "Saltrice already appears to be installed." && exit
sudo chown -R "$USER:$USER" "$SALTRICED"
[ -d "$XDG_CONFIG_HOME" ] && mv $XDG_CONFIG_HOME "${XDG_CONFIG_HOME}.orig" && echo "Backed up previous XDG_CONFIG_HOME to ${XDG_CONFIG_HOME}.orig"
mkdir -p $HOME/.cache/zsh && touch $HOME/.cache/zsh/history
while IFS=, read -r ln; do
    eval $(echo "$ln" | tr -d '\n' | awk -v sdir=$SALTRICED -v hdir=$HOME '{ print "ln -sf " sdir "/" $1 " " hdir "/" $2 }')
done < $SALTRICED/symlinks
