#!/usr/bin/env sh

[ -z $2 ] && num="5" || num="$2"

PLAYERD="$HOME/.cache/.playersel"
CURPLAY=$(cat $PLAYERD)

function selplayer(){
    CURPLAY=$(playerctl -l | dmenu -p "Select Player:" -c -l 10)
    [ ! -z $CURPLAY ] && echo "$CURPLAY" > $PLAYERD
}

if [ -z "$CURPLAY" ]; then
    if [ $(playerctl -l | wc -l) -gt 0 ]; then
        playerctl -l | tr '\n' ',' | awk -F',' '{print $1}' > $PLAYERD
        CURPLAY=$(cat $PLAYERD)
    else
        echo "No Players Available." && exit 1;
    fi
fi

alias pctl="playerctl -p $(head -n 1 $PLAYERD)"

case $1 in
    sel) selplayer ;;
    u*) pulsemixer --change-volume +"$num" ;;
    d*) pulsemixer --change-volume -"$num" ;;
    m|mute) pulsemixer --toggle-mute ;;
    truemute) pulsemixer --mute ;;
    next)  pctl next ;;
    prev)  pctl previous ;;
    play)  pctl play ;;
    pause) playerctl --all-players pause ;;
    playpause) pctl play-pause ;;
    restart) pctl next; pctl previous ;;
    now) pctl metadata --format "{{ artist }} - {{ title }}";;
    *) cat << EOF
actl: cli for PulseAudio + playerctl
Options:
    up NUM      Increase volume
    down NUM    Decrease volume
    mute        MUTE = !MUTE
    truemute    MUTE = TRUE
    next        Next track
    prev        Previous track
    play        PAUSED = FALSE
    pause       PAUSED = TRUE
    playpause   PAUSED = ! PAUSED
    restart     Restart current song
    now         Prints current song details to STDOUT as [Artist] - [Title]
    help        Print this message
EOF
esac
