#!/usr/bin/env bash
TARG=$(du -a $SALTRICED $HOME/school /usr/src | awk '{print $2}' | fzf)
if [ ! -z $TARG ]; then
    [ -d $TARG ] && cd $TARG || cd $(dirname "$TARG")
fi
[ ! -d $TARG ] && $EDITOR $TARG
