#!/usr/bin/env bash
function chkrec() {
    isrec="$(ps ax | grep 'x11grab' | grep -v 'grep' | awk '{print $1}')"
    [ ! -z "$isrec" ] && kill "$isrec" && exit
}
chkrec 2>&1 >/dev/null
fname="$HOME/vid/$(date +"%F_%T" | sed 's/-//g' | sed 's/://g')"
[ ! -z $1 ] && fname=$1;
offset=$(xrandr --query | awk '!/primary/ && / connected/' | awk '{print $3}' | awk -F'x' '{print $1}')
resol=$(xrandr --query | awk '/primary/ && / connected/' | awk '{print $4}' | awk -F'+' '{print $1}')
ffmpeg -f x11grab -video_size $resol -framerate 30 -draw_mouse 0 -i $DISPLAY.0+$offset,0 -f pulse -i default -c:v libx264 -preset ultrafast -crf 18 -pix_fmt yuv420p $fname.mkv > $HOME/vid/output.log 2>&1 < /dev/null &
#ffmpeg -f x11grab -video_size $resol -framerate 144 -draw_mouse 0 -i $DISPLAY.0+$offset,0 -f pulse -i default -c:v libx264 -preset ultrafast $fname.mkv > $HOME/vid/output.log 2>&1 < /dev/null &
