#!/usr/bin/env bash
function natives() { comm -23 <(sudo pacman -Qqetn | sort) <(sudo pacman -Sqg base base-devel | sort) | awk '{printf "N %s\n", $1}'; }
function aurs() { sudo pacman -Qqm | sort | awk '{printf "A %s\n", $1}'; }
{ natives & aurs; } | sort -k 2 | tr ' ' ',' | tr 'N' ' ' | grep -v 'nvidia'
