#!/usr/bin/env sh
ddname="dropdown_surf"
if pgrep -x i3 > /dev/null; then
    if xwininfo -tree -root | grep "$ddname"; then
        i3 "[instance=\"$ddname\"] scratchpad show; [instance=\"$ddname\"] move position center" > /dev/null 2>&1
    else
        i3 "exec --no-startup-id surf -Z messages.google.com"
    fi
fi
