#!/usr/bin/env sh

FTYPES="c,h,cpp,sh,py,tex"

function helpmsg(){
    echo "Format: $0 -f [filetype]"
    echo "Supported Filetypes:"
    echo "$FTYPES"
    exit
}

function mk_file(){
    case "$1" in
            cpp)
                OUTPUT="#include <iostream>\n\nusing namespace std;\n\nint main(int argc, char* argv[]){\n\t\n\treturn 0;\n}\n"
                break
                ;;
            c)
                OUTPUT="#include <stdio.h>\n\nint main(int argc, char* argv[]){\n\t\n\treturn 0;\n}\n"
                break
                ;;
            h)
                if [ -z "$TARG" ]; then
                    OUTPUT="#ifndef <++>\n#define <++>\n\n\n#endif\n"
                else
                    UTARG=$(echo "$TARG" | awk '{print toupper($0)}' | tr '.' '_')
                    OUTPUT="#ifndef ${UTARG}\n#define ${UTARG}\n\n<++>\n\n#endif\n"
                fi
                break
                ;;
            py)
                OUTPUT="#!/usr/bin/env python3\n\n\ndef main():\n    pass\n\nif __name__ == '__main__':\n    main()\n\n"
                CHMOD="1"
                break
                ;;
            tex)
                OFILE="$SNIPPETD/tex.tmpl"
                break
                ;;
            *)
                OUTPUT="#!/usr/bin/env $1\n"
                CHMOD="1"
                break
                ;;
    esac
}

while test $# -gt 0; do
    case "$1" in
            -h|--help)
                helpmsg
                ;;
            -f|--filetype)
                shift
                FILETYPE="$1"
                shift
                ;;
            -o|--output)
                shift
                TARG="$1"
                shift
                ;;
            *)
                helpmsg
                ;;
    esac
done

mk_file $FILETYPE
if [ ! -z "$TARG" ]; then
    [ ! -z "$OFILE" ] && cat "$OFILE" > $TARG || echo -e "$OUTPUT" > $TARG
    [ ! -z "$CHMOD" ] && chmod +x $TARG
else
    [ ! -z "$OFILE" ] && cat "$OFILE" || echo -e "$OUTPUT"
fi
