#!/usr/bin/env sh

FTYPES="c,cpp,sh,py"

function helpmsg(){
    echo "Format: $0 -f [filetype]"
    echo "Supported Filetypes:"
    echo "$FTYPES"
    exit
}

function mk_file(){
    case "$1" in
            cpp)
                OUTPUT="#include <iostream>\n\nusing namespace std;\n\nint \
                    main(int argc, char* argv[]){\n\t\n\treturn 0;\n}\n"
                break
                ;;
            c)
                OUTPUT="#include <stdio.h>\n\nint main(int argc, char* argv[]){\n\t\n\treturn 0;\n}\n"
                break
                ;;
            sh)
                OUTPUT="#!/usr/bin/env sh\n"
                break
                ;;
            py)
                OUTPUT="#!/usr/bin/env python3\n"
                break
                ;;
            *)
                OUTPUT="#!/usr/bin/env $1\n"
                break
                ;;
    esac
}

while test $# -gt 0; do
    case "$1" in
            -h|--help)
                helpmsg
                ;;
            -f|--filetype)
                shift
                mk_file $1
                shift
                ;;
            -o|--output)
                shift
                TARG="$1"
                shift
                ;;
            *)
                helpmsg
                ;;
    esac
done

if [ ! -z "$TARG" ]; then
    echo -e "$OUTPUT" > $TARG && chmod +x $TARG
else
    echo -e "$OUTPUT"
fi
