#!/usr/bin/env bash
[ -z $1 ] && exit 1;
find . -maxdepth 1 -iname "$1*" | grep -v "*.o" | sort -r | xargs -r -d '\n' -n 2 $EDITOR -O
# ls -l | awk '{print $9}' | grep -i "$1" | sort -r | xargs -r -d '\n' -n 2 $EDITOR -O
