#!/usr/bin/env sh

# Startup stuff

export BSPWM_CONFIGD="$HOME/.config/bspwm"

bspc rule -r "*"

xset -b &
sxhkd &
xcompmgr &
setwall &
mpd &
unclutter &
xautolock -time 15 -locker 'lckdwn'
sh $HOME/.config/polybar/launch.sh &

bspc monitor HDMI-0 -d 0 1 2 3 4 5 6 7 8 9
bspc monitor DP-4 -d 0 1 2 3 4 5 6 7 8 9

bspc desktop -f 1

bspc config border_width            2
bspc config window_gap              10
bspc config top_padding             24
bspc config bottom_padding          0
bspc config left_padding            0
bspc config right_padding           0
bspc config single_monocle          false
bspc config click_to_focus          true
bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config focus_follows_pointer   false
bspc config pointer_follows_focus   false

bspc rule -a scratchpad sticky=on state=floating hidden=on
$TERMINAL -c scratchpad -e $SCRIPTSD/scratch &
